// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_LOADED = "USER_LOADED";
export const NAME_UPDATED = "NAME_UPDATED";
export const PASSWORD_UPDATED = "PASSWORD_UPDATED";
export const PROFILE_PICTURE_UPLOADED = "PROFILE_PICTURE_UPLOADED";
export const PROFILE_PICTURE_REMOVED = "PROFILE_PICTURE_REMOVED";
export const LOGOUT = "LOGOUT";
export const SIDE_NAV_TOGGLED = "SIDE_NAV_TOGGLED";
export const AUTH_ERROR = "AUTH_ERROR";

// PROFILE
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_DELETED = "PROFILE_DELETED";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const USER_DELETED = "USER_DELETED";
export const PROFILE_ERROR = "PROFILE_ERROR";

// Posts
export const ALL_POSTS_LOADED = "ALL_POSTS_LOADED";
export const POST_LOADED = "POST_LOADED";
export const POST_ADDED = "POST_ADDED";
export const POST_REMOVED = "POST_REMOVED";
export const POST_ERROR = "POST_ERROR";
export const POST_IMAGE_UPLOADED = "POST_IMAGE_UPLOADED";

// Notification
export const MESSAGE_SENT = "MESSAGE_SENT";
export const MESSAGE_ERROR = "MESSAGE_ERROR";

export const ALL_MESSAGES_LOADED = "ALL_MESSAGES_LOADED";

export const GET_LOCATION = "GET_LOCATION";
export const LOCATION_ERROR = "LOCATION_ERROR";
